app:
  security:
    jwt:
      keystore-location: keys/keystore.jks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password
spring:
  h2:
    console:
      enabled: true
  profile:
    active: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: H2
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace